# Generated by Django 4.0.6 on 2022-08-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_voomuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voomuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
