# Generated by Django 4.0.6 on 2022-08-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skills_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
    ]
