# Generated by Django 4.0.6 on 2022-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_skills_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.TextField()),
                ('cert_image', models.ImageField(upload_to='certificates/')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
    ]
