# Generated by Django 4.0.6 on 2022-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certimages_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='main/main_photo/')),
            ],
            options={
                'verbose_name': 'Фото на главной странице',
                'verbose_name_plural': 'Фото на главной странице',
            },
        ),
        migrations.AlterField(
            model_name='certimages',
            name='cert_image',
            field=models.ImageField(upload_to='main/certificates/'),
        ),
    ]
