# Generated by Django 4.0.6 on 2022-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servicesimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimages',
            old_name='studio_photo',
            new_name='service_image',
        ),
        migrations.RemoveField(
            model_name='servicesimages',
            name='training_photo',
        ),
        migrations.AddField(
            model_name='servicesimages',
            name='button_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicesimages',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicesimages',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
