# Generated by Django 4.0.6 on 2022-08-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_studio_photo_servicesimages_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_photo', models.ImageField(upload_to='main/portfolio/')),
            ],
            options={
                'verbose_name': 'Фото для портфолио',
                'verbose_name_plural': 'Фото для портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Текст для портфолио',
                'verbose_name_plural': 'Текст для портфолио',
            },
        ),
        migrations.RenameModel(
            old_name='ServicesImages',
            new_name='Services',
        ),
    ]
