# Generated by Django 4.0.6 on 2022-08-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_portfolio_portfoliotext_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='PortfolioImages',
        ),
    ]
