# Generated by Django 4.0.6 on 2022-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_portfolio_portfolioimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
