# Generated by Django 4.0.6 on 2022-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_trainingcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourses',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
